import turtle
pen=turtle.Turtle()
# pen.speed(0)
pen.ht()
pen.color('pink')
pen.begin_fill()
for i in range(5):
    pen.circle(50)
    pen.left(72)
pen.end_fill()
pen.color('yellow')
pen.dot(50)
turtle.done()
import turtle
pen=turtle.Turtle()
pen.speed(0)
pen.ht()
pen.color('pink')
pen.begin_fill()
for i in range(5):
    pen.circle(50)
    pen.left(72)
pen.end_fill()
pen.color('green')
pen.begin_fill()
for i in range(5):
    pen.circle(35)
    pen.left(72)
pen.end_fill()
pen.color('red')
pen.begin_fill()
for i in range(5):
    pen.circle(20)
    pen.left(72)
pen.end_fill()
pen.color('yellow')
pen.dot(20)
turtle.done()