# import turtle
# pen=turtle.Turtle()
# pen.speed(0)
# pen.ht()
# pen.up()
# pen.goto(-125,-50)
# pen.down()
# a=pen.color('pink')
# pen.fd(250)
# pen.rt(600)
# b=pen.color('green')
# pen.fd(250)
# pen.rt(600)
# c=pen.color('blue')
# pen.fd(250)
# pen.rt(600)
# turtle.done()

# from turtle import *
# pen=Turtle()
# pen.pensize(5)
# a=input('请输入第一条边的颜色：')
# b=input('请输入第二条边的颜色：')
# c=input('请输入第三条边的颜色：')
# pen.pencolor(a)
# pen.fd(100)
# pen.lt(120)
# pen.pencolor(b)
# pen.fd(100)
# pen.lt(120)
# pen.pencolor(c)
# pen.fd(100)
# pen.lt(120)
# done()

import turtle
pen=turtle.Turtle()
pen.up()
pen.goto(0,-100)
pen.down()
pen.speed(0)
pen.ht()
pen.color('black','yellow')
pen.begin_fill()
pen.circle(150)
pen.end_fill()
pen.color('black','red')
pen.begin_fill()
pen.circle(150,steps=4)
pen.lt(45)
pen.fd(214)
pen.lt(135)
pen.fd(100)
pen.end_fill()
turtle.done()

